### ISSUE TITLE
sort template func fails for Pages

### ISSUE THREAD

**Issue by benzwu** [spf13/hugo#1330]
sorting list like this:

    {{ range sort .Site.Pages "Params.somefield" }}

causing error message: 

    ERROR: 2015/07/01 Error while rendering homepage: reflect: call of reflect.Value.FieldByName on ptr Value

**Comment by bep** [comment]
@derekperkins any input on what can be wrong here?

**Comment by bep** [comment]
OK, reading the doc, this isn't supported. "Params.somefield" isn't a field on Page. Sorting by nested map keys could maybe be implemented, but that is not on my todo-list.

Can you confirm that constructs like 

```
{{ range sort .Site.Pages "Title" }}
```

Work as expected?

**Comment by benzwu** [comment]
confirm, same result
````
{{ range sort .Site.Pages "Title" }}
	{{ .Title }}
{{ end }}
````
>ERROR: 2015/08/06 Error while rendering homepage: reflect: call of reflect.Value.FieldByName on ptr Value

**Comment by bep** [comment]
@derekperkins doesn't the sort func support pointers?

**Comment by tatsushid** [comment]
@bep it doesn't dereference pointer value.

**Comment by tatsushid** [comment]
Fixed in my local repository but I reconsider it's really enough to solve this

**Comment by derekperkins** [comment]
@bep I would have thought so, but I guess not. :) I haven't touched Hugo in 7-8 months, so I don't really remember. Should be easy enough to add an `Indirect` to support them.

@tatsushid Go ahead and submit your PR with the fix.

**Comment by tatsushid** [comment]
I sent a PR. Please see #1334

**Comment by AmrAbdulrahman** [comment]
Um trying to make a sort on user defined property as following:

in my pages:
```
+++
title= "bla bla bla"
parent = "parent"
index = 0 # each page is assigned a unique index
+++
```

and i try to apply sorting as following:
```
{{ range sort .Site.Pages ".Params.index" }}
    <a href="{{.RelPermalink}}">
          {{.Title}} {{.Params.index}}
    </a>
{{end}}
```

this doesn't fails at compilation, but the list is rendered empty.
I'm using hugo#0.15 which contains this PR merged: https://github.com/spf13/hugo/pull/1334

Am i missing something?

**Comment by AmrAbdulrahman** [comment]
Well, i was walking in the wrong direction.
I discovered that there's a default parameter is there just to be used for sorting, "**weight**"
So, the fix is:

`use "weight" instead of "index"`

and use weight

`{{ range sort .Site.Pages ".Weight" }}`

this fixed my issue, but it still a problem using **user defined properties** for sorting.

**Comment by bep** [comment]
This should be the same:

```
{{ range sort .Site.Pages.Sort }}
```

Sorts by Weigt (and then by title).
