### ISSUE TITLE
v0.15 hugo.exe freezing on Windows 10 64-bit

### ISSUE THREAD

**Issue by lukewilliamboswell** [spf13/hugo#1628]
I downloaded and try to verify the binary by running "hugo help" and it just sits there doing nothing. This happens in both command prompt and power shell. 

I downloaded and built the executable from go source (go get -v github.com/spf13/hugo) and the same thing happens.

However, when I use the v0.14 binary all is good and works as expected.

**Comment by anthonyfok** [comment]
Hi @lukewilliamboswell,

This problem was discovered and fixed by @tpng 19 or 20 hours ago, see Issue #1621.
In short, the bug only appears when the 32-bit hugo_0.15_windows_386.zip is used on 64-bit Windows.

In the meantime, please use the 64-bit hugo_0.15_windows_amd64.zip (amd64 = x86-64) binary instead, available at:

* https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_windows_amd64.zip

Please let us know if it solves the problem for you or not!

Thanks,
Anthony

**Comment by lukewilliamboswell** [comment]
How come I get the same issue building from source? 

Also I am certain that I have the amd64 binary. 

![untitled](https://cloud.githubusercontent.com/assets/2679227/11432238/959edc3e-94fd-11e5-920e-72fa905bc195.png)

![untitled](https://cloud.githubusercontent.com/assets/2679227/11432244/c988bd26-94fd-11e5-9d50-3f0a98f33d3b.png)

**Comment by tpng** [comment]
Could you please try to get the latest hugo using `go get -u -v github.com/spf13/hugo` and try to run `hugo help` again?

**Comment by tpng** [comment]
Please also run `hugo version` to see if it hang or not, thanks.

**Comment by lukewilliamboswell** [comment]
Downloaded latest version and rebuilt binary. It still hangs using "hugo version".

I can probably debug it for you guys later. I need to work on some other things but should get some free time later this weekend to look a little closer. I suspected it would be something really obvious considering the changes between the versions.  

So far I really like where you are going with HUGO. It looks great!

**Comment by anthonyfok** [comment]
Thank you @lukewilliamboswell and @tpng.

I am on my way out to choir practice, but will try tonight on my wife's Windows 8.1 64-bit and see if I can reproduce it.

**Comment by tpng** [comment]
Seems unrelated to https://github.com/spf13/hugo/issues/1621.

**Comment by tpng** [comment]
@lukewilliamboswell Please run `go test github.com/spf13/cobra` when you have time and see if there are any failed test.

**Comment by moorereason** [comment]
I've done some tests on a Windows 10 x64 system.  Everything works for me using HEAD.  Here's what I tested:

0. :white_check_mark: `hugo_0.15_windows_amd64.exe version`
0. :white_check_mark: `hugo_0.15_windows_amd64.exe server`
0. :white_check_mark: `hugo_0.15_windows_386.exe version`
0. :x: `hugo_0.15_windows_386.exe server`
0. :white_check_mark: `hugo_0.15_windows_386.exe server --renderToDisk`
0. :white_check_mark: `hugo_HEAD_windows_amd64.exe version`
0. :white_check_mark: `hugo_HEAD_windows_amd64.exe server`
0. :white_check_mark: `hugo_HEAD_windows_386.exe version`
0. :white_check_mark: `hugo_HEAD_windows_386.exe server`

In all cases, I ran Hugo from the `hugo/docs` folder.  I also ran tests for hugo (`go test ./...`) and cobra, both as amd64 and 386 (not sure it matters).

All that to say that I can't reproduce what @lukewilliamboswell is seeing with HEAD.  If building from source, make sure to update all dependencies (`go get -u -v github.com/spf13/hugo`) since the bug that shipped with 0.15 was from a dependent package.

**Comment by DerGroncki** [comment]
I have problem on windows 7 enterprise 64bit sp1. Hugo is not working at all. It seems that it is started 3 times.

![hugo on windows 7 enterprise 64bit sp1](https://cloud.githubusercontent.com/assets/2815398/11445768/4d9fb6a6-952f-11e5-9df8-391a8f23310e.jpg)

![taskmanager on windows 7 enterprise 64bit sp1](https://cloud.githubusercontent.com/assets/2815398/11445754/2b45fdb8-952f-11e5-9929-91c6e3d7b42a.jpg)

**Comment by tpng** [comment]
@DerGroncki Do you use any antivirus or firewall software, if yes, which one?

**Comment by DerGroncki** [comment]
@tpng avast 2015 - free edition

**Comment by tpng** [comment]
@DerGroncki Could you try to disable avast and run hugo again to see if it hang or not?

**Comment by DerGroncki** [comment]
Ok, I disabled avast. And now is working like a charm. You made my day. Thanks a lot.

**Comment by tpng** [comment]
Great, I guess you can add hugo to [avast exclusion list](http://www.getavast.net/support/managing-exceptions) and re-enable avast to see if it still works. Thanks!

@lukewilliamboswell Could you confirm if you are using avast too or not?

**Comment by lukewilliamboswell** [comment]
Yes I am using Avast free edition.

**Comment by tpng** [comment]
Can you try to disable DeepScreen by unchecking `Enable DeepScreen` in Avast setting and see if hugo works or not? Thanks.

**Comment by lukewilliamboswell** [comment]
Strange. Hugo 0.15 is working now... yet I haven't changed anything. Somehow between Saturday and now the issue has gone away. 

Checking windows update and there was an update that looks unrelated (KB3103688). Other than that my configuration hasn't changed.

Any ideas for things to check?

**Comment by tpng** [comment]
I guess Avast updated something on their part so the problem is not triggered anymore. Maybe try to use hugo as usual and see if any more issues come up.

**Comment by lukewilliamboswell** [comment]
@tpng  I managed to re-create the issue and can confirm that disabling DeepScreen eliminates the problem.

**Comment by hugouser** [comment]
I use Windows 7 Starter 32 bit on my Asus EEE laptop with SSD.
Today I tried about 2 hours to start "hugo server -w" and always recieved the problem as @lukewilliamboswell
But now I found the solution here. This is "hugo_0.15_windows_386.exe server --renderToDisk". Hugo works fine.
Thanks @moorereason

**Comment by vadimptr** [comment]
Downloaded zip file with Hugo from this source
https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_windows_amd64.zip

When I trying to install I recive error:
![Image of Yaktocat](http://dl1.joxi.net/drive/0014/0489/930281/160118/8a6c1e2537.jpg)

**Comment by anthonyfok** [comment]
Hi @vadimptr,

What you are seeing is completely normal.  Running `hugo` or `hugo_0.15_windows_amd64.exe` without any command-line parameters is to render an existing site (with config and content files) into the final HTML.  It seems you haven't created such a Hugo site yet, or you are in the wrong directory.

Please follow the QuickStart tutorial at http://gohugo.io/overview/quickstart to get started.
