### ISSUE TITLE
Static Local Website with Hugo (file:///)

### ISSUE THREAD

**Issue by JeremyBYU** [spf13/hugo#622]
Hey everyone,
  This question will probably seem a little strange to most people because most people dont deploy websites by distributing a folder of html files.  However I sometimes do this at work (with a network file share)  instead of having to deal with a server.

  What I'm trying to do is create a website with hugo that will build all my html files for a simple website and be able to open the html files with a browser.   To accomplish this I set `baseurl = path_to_file_share`. It correctly links all resources in the html files (css, images, javascripts).  I open the index.html homepage file in the file share and it loads correctly.  However all the link to other posts are broken and are replaced with  `<a href="#ZgotmplZ">`

A little googling brought me to this [page](http://stackoverflow.com/questions/14765395/why-am-i-seeing-zgotmplz-in-my-go-html-template-output) which basically says that Go is considering the html to be unsafe and is escaping it.  I'm guessing it is the file protocol in the link that it is considering to be unsafe (e.g. file:///).  

I know that there are some ways in the Go templating language to disable this functionality (see link).  Is there any way we can put a flag in hugo (maybe the config.toml) that will inactivate this html escaping feature.

Thanks for your help 

Jeremy

**Comment by rickb777** [comment]
This is a noble effort, but...

It would be good to fix the Hugo source code and submit a patch, instead of trying to fix links after they've been created.

**Comment by anthonyfok** [comment]
Hi @JeremyBYU and @rickb777,

It turns out this issue is very similar to #347 where the user wanted to use `irc://` links that got turned into `#ZgotmplZ`.  This was fixed by the addition of the `safeUrl` template function in commit 724cc0ddff3427a37b1fa4367880fce23bb4f1f8 on 19 Jan 2015, now in v0.13-DEV.  This new feature is documented around http://gohugo.io/templates/functions/#toc_12 (scroll down a bit to see it).

So, @JeremyBYU, with Hugo v0.13-DEV, you may now use a `baseurl = "file:///path/to/your/website/"` with `uglyurls = true` and have the links work by modifying your templates to use, for example, `<a href="{{ .Permalink | safeUrl }}>` rather than `<a href="{{ .Permalink }}">`.

Please let us know how it works out for you!

**Comment by rickb777** [comment]
This safeUrl solution seems like an ugly hack.

Why is it not possible to construct path-relative URLs so that safeUrl is not necessary?

**Comment by anthonyfok** [comment]
Hi @rickb777,

I think having a way to construct path-relative URLs is a worthy goal for v0.14 or v0.15.
I took a brief look at it some weeks ago, and thought we could implement something very similar to http://golang.org/pkg/path/filepath/#Rel, but for URL rather than file names.  But I was soon busy and haven't had time to follow up yet.  (I am still a Go learner.)

I agree that using `safeUrl` was an ugly hack; I was merely responding to the `<a href="#ZgotmplZ">` problem that @JeremyBYU reported in the original post.  Though an ugly hack, it works™ for those who need it until proper relative URLs support is available in Hugo.

But yes, not only do we welcome comments and suggestions, we welcome Pull Requests even more!  So, if you have time, we would love to receive a PR from you!  :wink:

**Comment by rgommers** [comment]
> This question will probably seem a little strange to most people because most people dont deploy websites by distributing a folder of html files. However I sometimes do this at work (with a network file share) instead of having to deal with a server.

This is not that uncommon actually. Another use case is letting users download a html site (e.g. docs for a software project) as a bundle to use offline.

This issue was closed, but the behavior is still not supported (nor documented as far as I can tell). Using something like:

   baseURL = "file:///path/to/networkfolder/doc/public/"

will not result in a working site whether `RelativeURLs` is set to true or false. If true, themes go missing completely, `hugo server` doesn't work (it changes `localhost:1313` to `localhost:1313/path/...`), etc.

Can this issue be reopened, or closed as wontfix?

**Comment by rgommers** [comment]
Update: after a couple of hours of digging I found the answer: `relativeURLs = "true"` *only* works in combination with `uglyURLs = "true"`. See https://github.com/gohugoio/hugo/issues/4642#issuecomment-382520968 for more details.

So no need to reopen this. I will see if I can find time for a PR to improve the Hugo docs - searching for terms like "portable", "offline", "deploying to a shared drive", etc. should lead users to a description of this behavior.

**Comment by inwardmovement** [comment]
I tried:
> 1. Do not set `baseURL`
> 2. Set `relativeURLs = "true"`
> 3. Set `uglyURLs = "true"`

But it doesn't work for me.

Couldn't we simply create a `hugo` parameter to build "for local" while taking care of mixed content not depending on `baseURL`, `relativeURLs`, `uglyURLs`, `canonifyURLs` (and so on)? `hugo --local` for example.

**Comment by nu8** [comment]
Not sure why the other person had trouble, but this did work for me (YAML):

~~~
relativeURLs: true
uglyURLs: true
~~~
